(function(){JuicySlider=function(p){var d,r,e,g,m,c,q,n,t,w,f,k,u,y,x,v,l,z,A,B=!1,C=0,h=this,D;u=function(a,b,c){for(var d in b)a[d]=b[d];if("options"==c)return a};y={elName:"jSlideContainer",sliderName:"jSlider",slideWrapperName:"jSlideWrapper",itemsize:"auto",visEl:1,scrollToEnd:!1,offset:0,scrollBy:0,carousel:!1,includeArrows:!1,keyCtrl:!1,replay:!1,tabCtrl:!1,slideSpeed:600,indicator:!1,direction:"vertical",responsive:!0,autoScroll:!1,ctrlNname:"jArrowNext",ctrlPname:"jArrowPrev",touch:!1,pause:!1,
culySliding:!1,current:0,easing:"ease-in-out",currentlySliding:!1};p&&"object"===typeof p&&(this.customOptions=!0,this.options=u(y,p,"options"));this.init=function(){this.options.current=this.options.carousel?0+this.options.offset:0;this._errorHandler(this.options);this._configureDependencies(this.options);this.options.carousel&&this._buildCarousel(this.options);this._buildLayout(this.options);A(this.options);!1!==this.options.autoScroll&&setInterval(D(),this.options.autoScroll.interval)};D=function(){!0!==
h.options.pause&&(h.options.currentlySliding=!1,h.slide("next",h.options))};this._errorHandler=function(a){if(null!==document.getElementById(a.elName))if(a.el=document.getElementById(a.elName),0<a.el.getElementsByClassName(a.slideWrapperName).length){if(a.slideWrapper=a.el.getElementsByClassName(a.slideWrapperName),void 0!==a.el){if(0<a.el.getElementsByTagName("ul").length&&void 0!==a.el.getElementsByTagName("ul")[0])a.slider=a.el.getElementsByTagName("ul"),a.trueSlideLength=a.slider[0].getElementsByTagName("li").length;
else throw Error("jSslider says: Slider could not be found in your dom");if(!1===a.autoScroll||!1===a.keyCtrl)if(0<a.el.getElementsByClassName(a.ctrlNname).length&&0<a.el.getElementsByClassName(a.ctrlPname).length)a.ctrlN=a.el.getElementsByClassName(a.ctrlNname),a.ctrlP=a.el.getElementsByClassName(a.ctrlPname);else throw Error("jSslider says: Arrows could not be found in your dom, you need something to controller the slider or automate it");else a.arrowCtrl=!1}}else throw Error("jSslider says: The Slidewrapper is missing , .slidewrapper>ul>li ..");
else throw Error("jSslider says: Container could not be found in your dom");};this._configureDependencies=function(a,b){a.el.className="sliderContainer jContainer "+a.direction;a.slider[0].className="jSlider";if(!1!==a.arrowCtrl||!1!==a.keyCtrl)a.ctrlN[0].classList.add("jArrow"),a.ctrlP[0].classList.add("jArrow")};this._buildCarousel=function(a){c=a.slideWrapper[0].getElementsByTagName("li");k=Math.floor(a.visEl/2);f=a.visEl%2;0<a.visEl%2&&1<a.visEl&&(k+=1,3<a.visEl&&(f=k-1));0<k&&0===f?f=k:0===k&&
0<f&&(k=f);f=k;0===a.slideWrapper[0].getElementsByClassName("active").length&&(c[0].classList.add("active"),"horizontal"==a.direction&&(this.options.current=1,d=-(100*this.options.current)+"%"));for(var b=0;b<k;b++)clone=c[b].cloneNode(!0),clone.classList.add("clone-right"),clone.classList.add("clone"),a.slider[0].appendChild(clone);for(b=f;0<b;b--){var e=c.length-k-C;3<=a.visEl&&(e+=1);clone=c[e-f].cloneNode(!0);clone.classList.add("clone-left");clone.classList.add("clone");a.slider[0].insertBefore(clone,
a.slider[0].firstChild);C++}};this._buildLayout=function(a){c=a.slider[0].children;r=c.length;0===a.slideWrapper[0].getElementsByClassName("active").length&&c[this.options.current].classList.add("active");a.replay||a.autoScroll||a.ctrlP[0].classList.add("disabled");a.el.style.overflow="hidden";e={width:"100%",height:"100%"};g={transition:"all "+a.slideSpeed+"ms "+a.easing};elWidth=a.el.clientWidth;elHeight=a.el.clientHeight;"horizontal"==a.direction?(slideStyle={width:100/c.length+"%"},a.includeArrows?
"auto"!==a.itemsize?(q=a.itemsize,n=35,t=a.el.clientWidth,x=t-2*n,v=Math.floor(x/q)>r?r:Math.floor(x/q),w=x/v,n=t-q*v,a.visEl=v,e={width:q*v+"px",height:"100%",left:n/2+"px",position:"absolute",overflow:"hidden"},m={width:n/2+"px"},slideStyle.width=q+"px",l=void 0!==f?-(100*(f-a.offset)/a.visEl)+"%":"0%",g={transition:"all "+a.slideSpeed+"ms "+a.easing,width:q*c.length+1+"px",height:"100%",transform:"translate3d("+l+",0,0)",webkitTransform:"translate3d("+l+",0,0)"},a.ctrlN[0].style.width=m.width,
a.ctrlP[0].style.width=m.width):(n=a.ctrlN[0].clientWidth,t=a.el.clientWidth,w=100/t*n*2,e={width:100-w+"%",height:"100%",left:w/2+"%",position:"absolute",overflow:"hidden"},l=void 0!==f?-(100*(f-a.offset)/a.visEl)+"%":"0%",g={transition:"all "+a.slideSpeed+"ms "+a.easing,width:100*c.length/a.visEl+"%",height:"100%",transform:"translate3d("+l+",0,0)",webkitTransform:"translate3d("+l+",0,0)"}):(n=a.ctrlN[0].clientWidth,t=a.el.clientWidth,e={width:"100%",height:"100%",position:"absolute",overflow:"hidden"},
l=void 0!==f?-(100*(f-a.offset)/c.length)+"%":"0%",0<a.offset&&1<a.visEl&&!a.carousel&&(l=100*(this.options.current+a.offset)/c.length+"%"),g={transition:"all "+a.slideSpeed+"ms "+a.easing,width:100*c.length/a.visEl+"%",height:"100%",transform:"translate3d("+l+",0,0)",webkitTransform:"translate3d("+l+",0,0)"})):(g={transition:"all "+a.slideSpeed+"ms "+a.easing,width:"100%",height:100*c.length+"%",top:"0%"},slideStyle={width:"100%",height:100/c.length+"%"});a.sliderStyle=g;a.wrapperStyle=e;a.arrowStyle=
m;u(a.slideWrapper[0].style,e,"style");u(a.slider[0].style,g,"style");for(a=0;a<c.length;a++)u(c[a].style,slideStyle,"style")};z=function(a){window.addEventListener("resize",function(){h._buildLayout(a);h.slide(void 0,a)})};A=function(a){!0===a.responsive&&!0!==a.carousel&&z(a);if(!1!==a.arrowCtrl||!1!==a.keyCtrl)a.ctrlN[0].addEventListener("click",function(){this.classList.contains("disabled")||h.next()}),a.ctrlP[0].addEventListener("click",function(){this.classList.contains("disabled")||h.prev()});
a.keyCtrl&&document.addEventListener("keydown",function(b){a.currentlySliding||("horizontal"==a.direction?39==b.keyCode?h.next():37==b.keyCode&&h.prev():40==b.keyCode?h.next():38==b.keyCode&&h.prev())})};this.destroy=function(){};this.rebuild=function(){this._buildLayout(this.options)};this.next=function(){this.options.currentlySliding||this.slide("next",this.options)};this.currentlySliding=function(){return this.options.currentlySliding};this.prev=function(){this.options.currentlySliding||this.slide("prev",
this.options)};this.pause=function(){this.options.currentlySliding||(this.options.pause=!0)};this.activeEl=function(){return this.options.current};this.slide=function(a,b){b.currentlySliding=!0;a&&("prev"==a?(0<b.current?(b.replay||(1<b.current?b.ctrlP[0].classList.remove("disabled"):b.ctrlP[0].classList.add("disabled"),b.current<=c.length&&b.ctrlN[0].classList.remove("disabled")),b.current--):b.replay?b.current=c.length-1:(b.ctrlN[0].classList.remove("disabled"),b.ctrlP[0].classList.add("disabled")),
b.replay&&b.current>=c.length-b.visEl+1&&(b.current=c.length-b.visEl),b.carousel&&0>=b.current&&window.setTimeout(function(){b.slider[0].style.transition="none";b.current=b.trueSlideLength;d="auto"!==b.itemsize?-(b.current*b.itemsize)+"px":-(100*b.current/c.length)+"%";for(var a=0;a<c.length;a++)c[a].classList.remove("active");c[b.current+b.offset].classList.add("jump");c[b.current+b.offset].classList.add("active");"horizontal"==b.direction?(b.slider[0].style.transform="translate3d("+d+",0,0)",b.slider[0].style.webkitTransform=
"translate3d("+d+",0,0)"):b.slider[0].style.top=-d+"%";removeJumpFlag=!0;window.setTimeout(function(){removeJumpFlag&&(b.slider[0].style.transition="all "+b.slideSpeed+"ms "+b.easing,c[b.current+b.offset].classList.remove("jump"))},40)},700)):(b.current<c.length-1?(b.current++,b.replay||(b.ctrlP[0].classList.remove("disabled"),b.scrollToEnd?b.current==c.length-b.offset&&b.ctrlN[0].classList.add("disabled"):b.current==c.length-b.visEl&&b.ctrlN[0].classList.add("disabled"))):b.replay&&(b.current=0),
b.replay&&b.current>=c.length-b.visEl+1&&(b.current=0),b.carousel&&(B=0<b.offset&&1<b.visEl?b.current>=b.trueSlideLength+b.offset:b.current>b.trueSlideLength+b.offset,!0===B&&window.setTimeout(function(){b.slider[0].style.transition="none";b.current=1;d="auto"!==b.itemsize?-(b.current*b.itemsize)+"px":-(100*b.current/c.length)+"%";for(var a=0;a<c.length;a++)c[a].classList.remove("active");c[b.current+b.offset].classList.add("jump");c[b.current+b.offset].classList.add("active");"horizontal"==b.direction?
(b.slider[0].style.transform="translate3d("+d+",0,0)",b.slider[0].style.webkitTransform="translate3d("+d+",0,0)"):b.slider[0].style.top=-d+"%";removeJumpFlag=!0;window.setTimeout(function(){removeJumpFlag&&(b.slider[0].style.transition="all "+b.slideSpeed+"ms "+b.easing,c[b.current+b.offset].classList.remove("jump"))},40)},700))));d="auto"!==b.itemsize?-(b.current*b.itemsize)+"px":-(100*b.current/c.length)+"%";0<b.offset&&1<b.visEl&&!b.carousel&&(d=-(100*(b.current-b.offset)/c.length)+"%");for(var e=
0;e<c.length;e++)c[e].classList.remove("active");c&&c[b.current]&&(b.carousel?c[b.current+b.offset].classList.add("active"):c[b.current].classList.add("active"));b.slider[0]&&("horizontal"==b.direction?(b.slider[0].style.transform="translate3d("+d+",0,0)",b.slider[0].style.webkitTransform="translate3d("+d+",0,0)"):(b.slider[0].style.transform="translate3d(0,"+d+",0)",b.slider[0].style.webkitTransform="translate3d(0,"+d+",0)"));window.setTimeout(function(){b.currentlySliding=!1},b.slideSpeed)}};"classList"in
document.createElement("_")||Object.defineProperty(HTMLElement.prototype,"classList",{get:function(){function p(e){return function(g){classes=d.className.split(/\s+/);index=classes.indexOf(g);e(classes,index,g);d.className=classes.join(" ")}}var d=this,r={add:p(function(e,d,m){~d||e.push(m)}),remove:p(function(e,d){~d&&e.splice(d,1)}),toggle:p(function(d,g,m){~g?d.splice(g,1):d.push(m)}),contains:function(e){return!!~d.className.split(/\s+/).indexOf(e)},item:function(e){return d.className.split(/\s+/)[e]||
null}};Object.defineProperty(r,"length",{get:function(){return d.className.split(/\s+/).length}});return r}})})();
