(function(){JuicySlider=function(p){var d,r,f,e,m,c,q,n,s,v,g,k,t,x,w,u,l,y,z=!1,A=0,h=this,B;t=function(b,a,c){for(var d in a)b[d]=a[d];if("options"==c)return b};x={elName:"jSlideContainer",sliderName:"jSlider",slideWrapperName:"jSlideWrapper",itemsize:"auto",visEl:1,scrollToEnd:!1,offset:0,scrollBy:0,carousel:!1,includeArrows:!1,keyCtrl:!1,replay:!1,tabCtrl:!1,slideSpeed:600,indicator:!1,direction:"vertical",responsive:!0,autoScroll:!1,ctrlNname:"jArrowNext",ctrlPname:"jArrowPrev",touch:!1,pause:!1,
culySliding:!1,current:0,easing:"ease-in-out",currentlySliding:!1};p&&"object"===typeof p&&(this.customOptions=!0,this.options=t(x,p,"options"));this.init=function(){this.options.current=this.options.carousel?0+this.options.offset:0;this._errorHandler(this.options);this._configureDependencies(this.options);this.options.carousel&&this._buildCarousel(this.options);this._buildLayout(this.options);this.initListeners(this.options)};B=function(){!0!==h.options.pause&&(h.options.currentlySliding=!1,h.slide("next",
h.options))};this._errorHandler=function(b){if(null!==document.getElementById(b.elName))if(b.el=document.getElementById(b.elName),0<b.el.getElementsByClassName(b.slideWrapperName).length){if(b.slideWrapper=b.el.getElementsByClassName(b.slideWrapperName),void 0!==b.el){if(0<b.el.getElementsByTagName("ul").length&&void 0!==b.el.getElementsByTagName("ul")[0])b.slider=b.el.getElementsByTagName("ul"),b.trueSlideLength=b.slider[0].getElementsByTagName("li").length;else throw Error("jSslider says: Slider could not be found in your dom");
if(!1===b.autoScroll||!1===b.keyCtrl)if(0<b.el.getElementsByClassName(b.ctrlNname).length&&0<b.el.getElementsByClassName(b.ctrlPname).length)b.ctrlN=b.el.getElementsByClassName(b.ctrlNname),b.ctrlP=b.el.getElementsByClassName(b.ctrlPname);else throw Error("jSslider says: Arrows could not be found in your dom, you need something to controller the slider or automate it");else b.arrowCtrl=!1}}else throw Error("jSslider says: The Slidewrapper is missing , .slidewrapper>ul>li ..");else throw Error("jSslider says: Container could not be found in your dom");
};this._configureDependencies=function(b,a){b.el.className="sliderContainer jContainer "+b.direction;b.slider[0].className="jSlider";if(!1!==b.arrowCtrl||!1!==b.keyCtrl)b.ctrlN[0].classList.add("jArrow"),b.ctrlP[0].classList.add("jArrow")};this._buildCarousel=function(b){c=b.slideWrapper[0].getElementsByTagName("li");k=Math.floor(b.visEl/2);g=b.visEl%2;0<b.visEl%2&&1<b.visEl&&(k+=1,3<b.visEl&&(g=k-1));0<k&&0===g?g=k:0===k&&0<g&&(k=g);g=k;for(var a=0;a<k;a++)clone=c[a].cloneNode(!0),clone.classList.add("clone-right"),
clone.classList.add("clone"),b.slider[0].appendChild(clone);for(a=g;0<a;a--){var d=c.length-k-A;3<=b.visEl&&(d+=1);clone=c[d-g].cloneNode(!0);clone.classList.add("clone-left");clone.classList.add("clone");b.slider[0].insertBefore(clone,b.slider[0].firstChild);A++}};this._buildLayout=function(b){c=b.slider[0].children;r=c.length;0===b.slideWrapper[0].getElementsByClassName("active").length&&c[this.options.current].classList.add("active");b.replay||b.autoScroll||b.ctrlP[0].classList.add("disabled");
b.el.style.overflow="hidden";f={width:"100%",height:"100%"};elWidth=b.el.clientWidth;elHeight=b.el.clientHeight;"horizontal"==b.direction?(slideStyle={width:100/c.length+"%"},b.includeArrows?"auto"!==b.itemsize?(q=b.itemsize,n=35,s=b.el.clientWidth,w=s-2*n,u=Math.floor(w/q)>r?r:Math.floor(w/q),v=w/u,n=s-q*u,b.visEl=u,f={width:q*u+"px",height:"100%",left:n/2+"px",position:"absolute",overflow:"hidden"},m={width:n/2+"px"},slideStyle.width=q+"px",l=void 0!==g?-(100*(g-b.offset)/b.visEl)+"%":"0%",e={transition:"all "+
b.slideSpeed+"ms "+b.easing,width:q*c.length+1+"px",height:"100%",transform:"translate3d("+l+",0,0)",webkitTransform:"translate3d("+l+",0,0)"},b.ctrlN[0].style.width=m.width,b.ctrlP[0].style.width=m.width):(n=b.ctrlN[0].clientWidth,s=b.el.clientWidth,v=100/s*n*2,f={width:100-v+"%",height:"100%",left:v/2+"%",position:"absolute",overflow:"hidden"},l=void 0!==g?-(100*(g-b.offset)/b.visEl)+"%":"0%",e={width:100*c.length/b.visEl+"%",height:"100%",transform:"translate3d("+l+",0,0)",webkitTransform:"translate3d("+
l+",0,0)"}):(n=b.ctrlN[0].clientWidth,s=b.el.clientWidth,f={width:"100%",height:"100%",position:"absolute",overflow:"hidden"},l=void 0!==g?-(100*(g-b.offset)/c.length)+"%":"0%",0<b.offset&&1<b.visEl&&!b.carousel&&(l=100*(this.options.current+b.offset)/c.length+"%"),e={width:100*c.length/b.visEl+"%",height:"100%",transform:"translate3d("+l+",0,0)",webkitTransform:"translate3d("+l+",0,0)"})):(e={transition:"all "+b.slideSpeed+"ms "+b.easing,width:"100%",height:100*c.length+"%",top:"0%"},slideStyle=
{width:"100%",height:100/c.length+"%"});b.sliderStyle=e;b.wrapperStyle=f;b.arrowStyle=m;t(b.slideWrapper[0].style,f,"style");t(b.slider[0].style,e,"style");for(var a=0;a<c.length;a++)t(c[a].style,slideStyle,"style");setTimeout(function(){b.slider[0].style.transition="all "+b.slideSpeed+"ms "+b.easing},500)};y=function(b){window.addEventListener("resize",function(){h._buildLayout(b);h.slide(void 0,b)})};this.initListeners=function(b){!0===b.responsive&&!0!==b.carousel&&y(b);if(!1!==b.arrowCtrl||!1!==
b.keyCtrl)b.ctrlN[0].addEventListener("click",function(){this.classList.contains("disabled")||h.next()}),b.ctrlP[0].addEventListener("click",function(){this.classList.contains("disabled")||h.prev()});b.keyCtrl&&document.addEventListener("keydown",function(a){b.currentlySliding||("horizontal"==b.direction?39==a.keyCode?h.next():37==a.keyCode&&h.prev():40==a.keyCode?h.next():38==a.keyCode&&h.prev())});!1!==this.options.autoScroll&&setInterval(B,this.options.autoScroll.interval)};this.destroy=function(){};
this.rebuild=function(){this._buildLayout(this.options)};this.next=function(){this.options.currentlySliding||this.slide("next",this.options)};this.currentlySliding=function(){return this.options.currentlySliding};this.prev=function(){this.options.currentlySliding||this.slide("prev",this.options)};this.pause=function(){this.options.currentlySliding||(this.options.pause=!0)};this.activeEl=function(){return this.options.current};this.slide=function(b,a){a.currentlySliding=!0;b&&("prev"==b?(0<a.current?
(a.replay||(1<a.current?a.ctrlP[0].classList.remove("disabled"):a.ctrlP[0].classList.add("disabled"),a.current<=c.length&&a.ctrlN[0].classList.remove("disabled")),a.current--):a.replay?a.current=c.length-1:(a.ctrlN[0].classList.remove("disabled"),a.ctrlP[0].classList.add("disabled")),a.replay&&a.current>=c.length-a.visEl+1&&(a.current=c.length-a.visEl),a.carousel&&0>=a.current&&window.setTimeout(function(){a.slider[0].style.transition="none";a.current=a.trueSlideLength;d="auto"!==a.itemsize?-(a.current*
a.itemsize)+"px":-(100*a.current/c.length)+"%";for(var b=0;b<c.length;b++)c[b].classList.remove("active");c[a.current+a.offset].classList.add("jump");c[a.current+a.offset].classList.add("active");"horizontal"==a.direction?(a.slider[0].style.transform="translate3d("+d+",0,0)",a.slider[0].style.webkitTransform="translate3d("+d+",0,0)"):a.slider[0].style.top=-d+"%";removeJumpFlag=!0;window.setTimeout(function(){removeJumpFlag&&(a.slider[0].style.transition="all "+a.slideSpeed+"ms "+a.easing,c[a.current+
a.offset].classList.remove("jump"))},40)},700)):(a.current<c.length-1?(a.current++,a.replay||(a.ctrlP[0].classList.remove("disabled"),a.scrollToEnd?a.current==c.length-a.offset&&a.ctrlN[0].classList.add("disabled"):a.current==c.length-a.visEl&&a.ctrlN[0].classList.add("disabled"))):a.replay&&(a.current=0),a.replay&&a.current>=c.length-a.visEl+1&&(a.current=0),a.carousel&&(z=0<a.offset&&1<a.visEl?a.current>=a.trueSlideLength+a.offset:a.current>a.trueSlideLength+a.offset,!0===z&&window.setTimeout(function(){a.slider[0].style.transition=
"none";a.current=1;d="auto"!==a.itemsize?-(a.current*a.itemsize)+"px":-(100*a.current/c.length)+"%";for(var b=0;b<c.length;b++)c[b].classList.remove("active");c[a.current+a.offset].classList.add("jump");c[a.current+a.offset].classList.add("active");"horizontal"==a.direction?(a.slider[0].style.transform="translate3d("+d+",0,0)",a.slider[0].style.webkitTransform="translate3d("+d+",0,0)"):a.slider[0].style.top=-d+"%";removeJumpFlag=!0;window.setTimeout(function(){removeJumpFlag&&(a.slider[0].style.transition=
"all "+a.slideSpeed+"ms "+a.easing,c[a.current+a.offset].classList.remove("jump"))},40)},700))));d="auto"!==a.itemsize?-(a.current*a.itemsize)+"px":-(100*a.current/c.length)+"%";0<a.offset&&1<a.visEl&&!a.carousel&&(d=-(100*(a.current-a.offset)/c.length)+"%");for(var f=0;f<c.length;f++)c[f].classList.remove("active");c&&c[a.current]&&(a.carousel?c[a.current+a.offset].classList.add("active"):c[a.current].classList.add("active"));a.slider[0]&&("horizontal"==a.direction?(a.slider[0].style.transform="translate3d("+
d+",0,0)",a.slider[0].style.webkitTransform="translate3d("+d+",0,0)"):(a.slider[0].style.transform="translate3d(0,"+d+",0)",a.slider[0].style.webkitTransform="translate3d(0,"+d+",0)"));window.setTimeout(function(){a.currentlySliding=!1},a.slideSpeed)}};"classList"in document.createElement("_")||Object.defineProperty(HTMLElement.prototype,"classList",{get:function(){function p(f){return function(e){classes=d.className.split(/\s+/);index=classes.indexOf(e);f(classes,index,e);d.className=classes.join(" ")}}
var d=this,r={add:p(function(d,e,m){~e||d.push(m)}),remove:p(function(d,e){~e&&d.splice(e,1)}),toggle:p(function(d,e,m){~e?d.splice(e,1):d.push(m)}),contains:function(f){return!!~d.className.split(/\s+/).indexOf(f)},item:function(f){return d.className.split(/\s+/)[f]||null}};Object.defineProperty(r,"length",{get:function(){return d.className.split(/\s+/).length}});return r}})})();
