(function(){JuicySlider=function(n){var d,q,e,g,l,c,p,m,r,w,f,h,s,y,x,t,k,z,A,u,B=!1,C=current=0,v=this;s=function(a,b,c){for(var d in b)a[d]=b[d];if("options"==c)return a};y={elName:"jSlideContainer",sliderName:"jSlider",slideWrapperName:"jSlideWrapper",itemsize:"auto",visEl:1,scrollToEnd:!1,offset:0,scrollBy:0,carousel:!1,includeArrows:!1,keyCtrl:!1,replay:!1,tabCtrl:!1,slideSpeed:600,indicator:!1,direction:"vertical",responsive:!0,autoScroll:!1,ctrlNname:"jArrowNext",ctrlPname:"jArrowPrev",touch:!1,
pause:!1,currentlySliding:!1};n&&"object"===typeof n&&(this.customOptions=!0,this.options=s(y,n,"options"));this.init=function(){this.options.current=this.options.carousel?0+this.options.offset:0;this._errorHandler(this.options);this._configureDependencies(this.options);this.options.carousel&&this._buildCarousel(this.options);this.options.extCtrl&&this.bindExtCtrl(this.options);!1!==this.options.tabCtrl&&this._bindTabCtrl(this.options);this.options.extSlider&&this.ConnectToExtSlider(this.options);
this._buildLayout(this.options);A(this.options);var a=this;!1!==this.options.autoScroll&&this.options.autoScroll.on&&setInterval(function(){!0!==a.options.pause&&(a.options.currentlySliding=!1,u("next",a.options))},this.options.autoScroll.interval)};this._errorHandler=function(a){if(null!==document.getElementById(a.elName))a.el=document.getElementById(a.elName);else throw Error("jSslider says: Container could not be found in your dom");if(null!==a.el.getElementsByTagName("ul")||void 0!==a.el.getElementsByTagName("ul"))a.slider=
a.el.getElementsByTagName("ul"),a.trueSlideLength=a.slider[0].getElementsByTagName("li").length;else throw Error("jSslider says: Slider could not be found in your dom");if(null!==a.el.getElementsByClassName(a.slideWrapperName))a.slideWrapper=a.el.getElementsByClassName(a.slideWrapperName);else throw Error("jSslider says: The Slidewrapper is missing , .slidewrapper>ul>li ..");if(!1===a.autoScroll)if(0<a.el.getElementsByClassName(a.ctrlNname).length&&0<a.el.getElementsByClassName(a.ctrlPname).length)a.ctrlN=
a.el.getElementsByClassName(a.ctrlNname),a.ctrlP=a.el.getElementsByClassName(a.ctrlPname);else throw Error("jSslider says: Arrows could not be found in your dom, you need something to controller the slider or automate it");else 0<a.el.getElementsByClassName(a.ctrlNname).length&&0<a.el.getElementsByClassName(a.ctrlPname).length?(a.ctrlN=a.el.getElementsByClassName(a.ctrlNname),a.ctrlP=a.el.getElementsByClassName(a.ctrlPname)):a.arrowCtrl=!1;if(!1!==a.tabCtrl)if(null!==document.getElementById(a.tabCtrl.el)){a.tabCtrl.domEl=
document.getElementById(a.tabCtrl.el);if(null!==a.tabCtrl.domEl.getElementsByTagName("ul")||void 0!==a.tabCtrl.domEl.getElementsByTagName("ul"))if(a.tabCtrl.slider=a.tabCtrl.domEl.getElementsByTagName("ul"),void 0!==a.tabCtrl.slider[0])a.tabCtrl.trueSlideLength=a.tabCtrl.slider[0].getElementsByTagName("li").length;else throw Error("jSlider says: Tab Wrapper is not available in your dom");else throw Error("jSlider says: Tab Children are not available in your dom");if(a.trueSlideLength!=a.tabCtrl.trueSlideLength)throw Error("jSlider says: Tab and Slide amounts dont match");
}else throw Error("jSlider says: Tab Wrapper is not available in your dom");};this._configureDependencies=function(a,b){a.el.className="sliderContainer jContainer "+a.direction;a.slider[0].className="jSlider";!1!==a.arrowCtrl&&(a.ctrlN[0].classList.add("jArrow"),a.ctrlP[0].classList.add("jArrow"))};this._buildCarousel=function(a){c=a.slideWrapper[0].getElementsByTagName("li");h=Math.floor(a.visEl/2);f=a.visEl%2;0<a.visEl%2&&1<a.visEl&&(h+=1,3<a.visEl&&(f=h-1));0<h&&0===f?f=h:0===h&&0<f&&(h=f);f=h;
0===a.slideWrapper[0].getElementsByClassName("active").length&&(c[0].classList.add("active"),"horizontal"==a.direction&&(current=1,d=-(100*current)+"%"));for(var b=0;b<h;b++)clone=c[b].cloneNode(!0),clone.classList.add("clone-right"),clone.classList.add("clone"),a.slider[0].appendChild(clone);for(b=f;0<b;b--){var e=c.length-h-C;3<=a.visEl&&(e+=1);clone=c[e-f].cloneNode(!0);clone.classList.add("clone-left");clone.classList.add("clone");a.slider[0].insertBefore(clone,a.slider[0].firstChild);C++}};this._bindTabCtrl=
function(a){};this._buildLayout=function(a){c=a.slideWrapper[0].getElementsByTagName("li");q=c.length;0===a.slideWrapper[0].getElementsByClassName("active").length&&c[this.options.current].classList.add("active");a.replay||a.autoScroll||a.ctrlP[0].classList.add("disabled");a.el.style.overflow="hidden";e={width:"100%",height:"100%"};g={transition:"all "+a.slideSpeed+"ms ease-in-out"};elWidth=a.el.clientWidth;elHeight=a.el.clientHeight;"horizontal"==a.direction?(slideStyle={width:100/c.length+"%"},
a.includeArrows?"auto"!==a.itemsize?(p=a.itemsize,m=35,r=a.el.clientWidth,x=r-2*m,t=Math.floor(x/p)>q?q:Math.floor(x/p),w=x/t,m=r-p*t,a.visEl=t,e={width:p*t+"px",height:"100%",left:m/2+"px",position:"absolute",overflow:"hidden"},l={width:m/2+"px"},slideStyle.width=p+"px",k=void 0!==f?-(100*(f-a.offset)/a.visEl)+"%":"0%",g={transition:"all "+a.slideSpeed+"ms ease-in-out",width:p*c.length+1+"px",height:"100%",transform:"translate3d("+k+",0,0)",webkitTransform:"translate3d("+k+",0,0)"},a.ctrlN[0].style.width=
l.width,a.ctrlP[0].style.width=l.width):(m=a.ctrlN[0].clientWidth,r=a.el.clientWidth,w=100/r*m*2,e={width:100-w+"%",height:"100%",left:w/2+"%",position:"absolute",overflow:"hidden"},k=void 0!==f?-(100*(f-a.offset)/a.visEl)+"%":"0%",g={transition:"all "+a.slideSpeed+"ms ease-in-out",width:100*c.length/a.visEl+"%",height:"100%",transform:"translate3d("+k+",0,0)",webkitTransform:"translate3d("+k+",0,0)"}):(m=a.ctrlN[0].clientWidth,r=a.el.clientWidth,e={width:"100%",height:"100%",position:"absolute",
overflow:"hidden"},k=void 0!==f?-(100*(f-a.offset)/c.length)+"%":"0%",0<a.offset&&1<a.visEl&&!a.carousel&&(k=100*(a.current+a.offset)/c.length+"%"),g={transition:"all "+a.slideSpeed+"ms ease-in-out",width:100*c.length/a.visEl+"%",height:"100%",transform:"translate3d("+k+",0,0)",webkitTransform:"translate3d("+k+",0,0)"})):(g={transition:"all "+a.slideSpeed+"ms ease-in-out",width:"100%",height:100*c.length+"%",top:"0%"},slideStyle={width:"100%",height:100/c.length+"%"});a.sliderStyle=g;a.wrapperStyle=
e;a.arrowStyle=l;s(a.slideWrapper[0].style,e,"style");s(a.slider[0].style,g,"style");for(a=0;a<c.length;a++)s(c[a].style,slideStyle,"style")};z=function(a){window.addEventListener("resize",function(){v._buildLayout(a);u(void 0,a)})};A=function(a){!0===a.responsive&&!0!==a.carousel&&z(a);!1!==a.arrowCtrl&&(a.ctrlN[0].addEventListener("click",function(){this.classList.contains("disabled")||v.next()}),a.ctrlP[0].addEventListener("click",function(){this.classList.contains("disabled")||v.prev()}));a.keyCtrl&&
document.addEventListener("keydown",function(b){a.currentlySliding||(39==b.keyCode?v.next():37==b.keyCode&&v.prev())})};this.destroy=function(){};this.rebuild=function(){this._buildLayout(this.options)};this.next=function(){this.options.currentlySliding||u("next",this.options)};this.currentlySliding=function(){return this.options.currentlySliding};this.prev=function(){this.options.currentlySliding||u("prev",this.options)};this.pause=function(){this.options.currentlySliding||(this.options.pause=!0)};
this.activeEl=function(){return this.options.current};u=function(a,b){b.currentlySliding=!0;a&&("prev"==a?(0<b.current?(b.replay||(1<b.current?b.ctrlP[0].classList.remove("disabled"):b.ctrlP[0].classList.add("disabled"),b.current<c.length&&b.ctrlN[0].classList.remove("disabled")),b.current--):b.replay?b.current=c.length-1:(b.ctrlN[0].classList.remove("disabled"),b.ctrlP[0].classList.add("disabled")),b.replay&&b.current>=c.length-b.visEl+1&&(b.current=c.length-b.visEl),b.carousel&&0>=b.current&&window.setTimeout(function(){b.slider[0].style.transition=
"none";b.current=b.trueSlideLength;d="auto"!==b.itemsize?-(b.current*b.itemsize)+"px":-(100*b.current/c.length)+"%";for(var a=0;a<c.length;a++)c[a].classList.remove("active");c[b.current+b.offset].classList.add("jump");c[b.current+b.offset].classList.add("active");"horizontal"==b.direction?(b.slider[0].style.transform="translate3d("+d+",0,0)",b.slider[0].style.webkitTransform="translate3d("+d+",0,0)"):b.slider[0].style.top=-d+"%";removeJumpFlag=!0;window.setTimeout(function(){removeJumpFlag&&(b.slider[0].style.transition=
"all "+b.slideSpeed+"ms ease-in-out",c[b.current+b.offset].classList.remove("jump"))},40)},700)):(b.current<c.length-1?(b.current++,b.replay||(b.ctrlP[0].classList.remove("disabled"),b.scrollToEnd?b.current==c.length-b.offset&&b.ctrlN[0].classList.add("disabled"):b.current==c.length-b.visEl-1&&b.ctrlN[0].classList.add("disabled"))):b.replay&&(b.current=0),b.replay&&b.current>=c.length-b.visEl+1&&(b.current=0),b.carousel&&(B=0<b.offset&&1<b.visEl?b.current>=b.trueSlideLength+b.offset:b.current>b.trueSlideLength+
b.offset,!0===B&&window.setTimeout(function(){b.slider[0].style.transition="none";b.current=1;d="auto"!==b.itemsize?-(b.current*b.itemsize)+"px":-(100*b.current/c.length)+"%";for(var a=0;a<c.length;a++)c[a].classList.remove("active");c[b.current+b.offset].classList.add("jump");c[b.current+b.offset].classList.add("active");"horizontal"==b.direction?(b.slider[0].style.transform="translate3d("+d+",0,0)",b.slider[0].style.webkitTransform="translate3d("+d+",0,0)"):b.slider[0].style.top=-d+"%";removeJumpFlag=
!0;window.setTimeout(function(){removeJumpFlag&&(b.slider[0].style.transition="all "+b.slideSpeed+"ms ease-in-out",c[b.current+b.offset].classList.remove("jump"))},40)},700))));d="auto"!==b.itemsize?-(b.current*b.itemsize)+"px":-(100*b.current/c.length)+"%";0<b.offset&&1<b.visEl&&!b.carousel&&(d=-(100*(b.current-b.offset)/c.length)+"%");for(var e=0;e<c.length;e++)c[e].classList.remove("active");c&&c[b.current]&&(b.carousel?c[b.current+b.offset].classList.add("active"):c[b.current].classList.add("active"));
b.slider[0]&&("horizontal"==b.direction?(b.slider[0].style.transform="translate3d("+d+",0,0)",b.slider[0].style.webkitTransform="translate3d("+d+",0,0)"):b.slider[0].style.top=-d+"%");window.setTimeout(function(){b.currentlySliding=!1},b.slideSpeed)}};"classList"in document.createElement("_")||Object.defineProperty(HTMLElement.prototype,"classList",{get:function(){function n(e){return function(g){classes=d.className.split(/\s+/);index=classes.indexOf(g);e(classes,index,g);d.className=classes.join(" ")}}
var d=this,q={add:n(function(e,d,l){~d||e.push(l)}),remove:n(function(e,d){~d&&e.splice(d,1)}),toggle:n(function(d,g,l){~g?d.splice(g,1):d.push(l)}),contains:function(e){return!!~d.className.split(/\s+/).indexOf(e)},item:function(e){return d.className.split(/\s+/)[e]||null}};Object.defineProperty(q,"length",{get:function(){return d.className.split(/\s+/).length}});return q}})})();
